//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAdminTool.OTCSContentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Core.service.livelink.opentext.com", ConfigurationName="OTCSContentService.ContentService")]
    public interface ContentService {
        
        // CODEGEN: Generating message contract since message DownloadContentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/DownloadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/DownloadContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        myAdminTool.OTCSContentService.DownloadContentResponse DownloadContent(myAdminTool.OTCSContentService.DownloadContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/DownloadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/DownloadContentResponse")]
        System.Threading.Tasks.Task<myAdminTool.OTCSContentService.DownloadContentResponse> DownloadContentAsync(myAdminTool.OTCSContentService.DownloadContentRequest request);
        
        // CODEGEN: Generating message contract since message UploadContentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/UploadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/UploadContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        myAdminTool.OTCSContentService.UploadContentResponse UploadContent(myAdminTool.OTCSContentService.UploadContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/UploadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/UploadContentResponse")]
        System.Threading.Tasks.Task<myAdminTool.OTCSContentService.UploadContentResponse> UploadContentAsync(myAdminTool.OTCSContentService.UploadContentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.ecm.opentext.com")]
    public partial class OTAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileAtts))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public abstract partial class ServiceDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class FileAtts : ServiceDataObject {
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private string fileNameField;
        
        private System.Nullable<long> fileSizeField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
                this.RaisePropertyChanged("ModifiedDate");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadContent", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class DownloadContentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public myAdminTool.OTCSContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public string contextID;
        
        public DownloadContentRequest() {
        }
        
        public DownloadContentRequest(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID) {
            this.OTAuthentication = OTAuthentication;
            this.contextID = contextID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadContentResponse", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class DownloadContentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public myAdminTool.OTCSContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public System.IO.Stream DownloadContentResult;
        
        public DownloadContentResponse() {
        }
        
        public DownloadContentResponse(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, System.IO.Stream DownloadContentResult) {
            this.OTAuthentication = OTAuthentication;
            this.DownloadContentResult = DownloadContentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadContent", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UploadContentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public myAdminTool.OTCSContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
        public string contextID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
        public myAdminTool.OTCSContentService.FileAtts fileAtts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public System.IO.Stream contents;
        
        public UploadContentRequest() {
        }
        
        public UploadContentRequest(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID, myAdminTool.OTCSContentService.FileAtts fileAtts, System.IO.Stream contents) {
            this.OTAuthentication = OTAuthentication;
            this.contextID = contextID;
            this.fileAtts = fileAtts;
            this.contents = contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadContentResponse", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UploadContentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public myAdminTool.OTCSContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public string UploadContentResult;
        
        public UploadContentResponse() {
        }
        
        public UploadContentResponse(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string UploadContentResult) {
            this.OTAuthentication = OTAuthentication;
            this.UploadContentResult = UploadContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContentServiceChannel : myAdminTool.OTCSContentService.ContentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentServiceClient : System.ServiceModel.ClientBase<myAdminTool.OTCSContentService.ContentService>, myAdminTool.OTCSContentService.ContentService {
        
        public ContentServiceClient() {
        }
        
        public ContentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myAdminTool.OTCSContentService.DownloadContentResponse myAdminTool.OTCSContentService.ContentService.DownloadContent(myAdminTool.OTCSContentService.DownloadContentRequest request) {
            return base.Channel.DownloadContent(request);
        }
        
        public System.IO.Stream DownloadContent(ref myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID) {
            myAdminTool.OTCSContentService.DownloadContentRequest inValue = new myAdminTool.OTCSContentService.DownloadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            myAdminTool.OTCSContentService.DownloadContentResponse retVal = ((myAdminTool.OTCSContentService.ContentService)(this)).DownloadContent(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.DownloadContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myAdminTool.OTCSContentService.DownloadContentResponse> myAdminTool.OTCSContentService.ContentService.DownloadContentAsync(myAdminTool.OTCSContentService.DownloadContentRequest request) {
            return base.Channel.DownloadContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<myAdminTool.OTCSContentService.DownloadContentResponse> DownloadContentAsync(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID) {
            myAdminTool.OTCSContentService.DownloadContentRequest inValue = new myAdminTool.OTCSContentService.DownloadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            return ((myAdminTool.OTCSContentService.ContentService)(this)).DownloadContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myAdminTool.OTCSContentService.UploadContentResponse myAdminTool.OTCSContentService.ContentService.UploadContent(myAdminTool.OTCSContentService.UploadContentRequest request) {
            return base.Channel.UploadContent(request);
        }
        
        public string UploadContent(ref myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID, myAdminTool.OTCSContentService.FileAtts fileAtts, System.IO.Stream contents) {
            myAdminTool.OTCSContentService.UploadContentRequest inValue = new myAdminTool.OTCSContentService.UploadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            inValue.fileAtts = fileAtts;
            inValue.contents = contents;
            myAdminTool.OTCSContentService.UploadContentResponse retVal = ((myAdminTool.OTCSContentService.ContentService)(this)).UploadContent(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.UploadContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myAdminTool.OTCSContentService.UploadContentResponse> myAdminTool.OTCSContentService.ContentService.UploadContentAsync(myAdminTool.OTCSContentService.UploadContentRequest request) {
            return base.Channel.UploadContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<myAdminTool.OTCSContentService.UploadContentResponse> UploadContentAsync(myAdminTool.OTCSContentService.OTAuthentication OTAuthentication, string contextID, myAdminTool.OTCSContentService.FileAtts fileAtts, System.IO.Stream contents) {
            myAdminTool.OTCSContentService.UploadContentRequest inValue = new myAdminTool.OTCSContentService.UploadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            inValue.fileAtts = fileAtts;
            inValue.contents = contents;
            return ((myAdminTool.OTCSContentService.ContentService)(this)).UploadContentAsync(inValue);
        }
    }
}
